### ISSUE TITLE
Consider VueJS Version

### ISSUE THREAD

**Issue by vinicius73** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#1]
Hi!
This is a very interesting project, it would be nice to have a version of it in vuejs http://vuejs.org

**Comment by mrholek** [comment]
Now I'm working on Angular2 and React version but I will check http://vuejs.org

**Comment by aemadrid** [comment]
+1 please!

**Comment by Lee2011** [comment]
+1 please!

**Comment by joaosalless** [comment]
+1 please!

**Comment by pess0a** [comment]
+1 please

**Comment by vs0uz4** [comment]
+1 please

**Comment by fucazu** [comment]
+1 please

**Comment by VictorAvelar** [comment]
+1 please.

**Comment by RezaHaidari** [comment]
+1

**Comment by mattjcowan** [comment]
+1

**Comment by guanchor** [comment]
+1

There is some advance in this way? May be some expected

**Comment by mrholek** [comment]
Vue.js version is almost ready, I'm going to publish it at the end of next week.
<img width="1920" alt="zrzut ekranu 2017-02-25 o 18 41 02" src="https://cloud.githubusercontent.com/assets/3524167/23333344/30f2f294-fb8a-11e6-93b5-fd860a2c0d5e.png">

**Comment by mrholek** [comment]
Vue.JS Version is ready

**Comment by aemadrid** [comment]
Very cool, thx!
