### ISSUE TITLE
Angular2_CLI_Starter  Table can't responsive

### ISSUE THREAD

**Issue by TopDuke** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#101]
scss core/_layout.scss
.app-body {
    display: flex;
    flex-grow:1;
    flex-direction: row;
    overflow-x: hidden;

   .main {
     flex: 1;
   }

  .sidebar {
    // $sidebar-width is the width of the columns
    flex: 0 0 $sidebar-width;
    // put the nav on the left
    order: -1;
  }

  .aside-menu {
    // $aside-menu-width is the width of the columns
    flex: 0 0 $aside-menu-width;
  }
}
when delete .app-body{ display:flex;}  table can responsive ,.but layout will be crash.
please how to solve it . thanks all

**Comment by mrholek** [comment]
Do you have any screenshots?

**Comment by TopDuke** [comment]
in Angular2_CLI_Starter Project 

dashboard.component.html code

```
<div class="animated fadeIn">
    Hello World!
</div>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
      <th>Username</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
            <td>Otto</td>
      <td>@mdo</td>

    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
            <td>Otto</td>
      <td>@mdo</td>

    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
            <td>Otto</td>
      <td>@mdo</td>

    </tr>
  </tbody>
</table>
```
in mobile picture can't responsive 
![321](https://cloud.githubusercontent.com/assets/5657710/22624434/1bdfe5de-ebb7-11e6-8cfb-e1c8960ce07c.jpg)

**Comment by tommyalvarez** [comment]
+1. Responsive tables aren't working on CoreUI @mrholek

**Comment by mohd-isa** [comment]
facing same issue.
