### ISSUE TITLE
Sidebar disappears on mobile view

### ISSUE THREAD

**Issue by iamonuwa** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#106]
The sidebar menu is not visible, can't be toggled on mobile view.

**Comment by iamonuwa** [comment]
I've resolved this issue,

On line 61 (_layout.scss) change from -200px to 0

**Comment by mrholek** [comment]
Do you use latest version of coreui?

**Comment by iamonuwa** [comment]
Yes, am using the latest version of coreui (1.0.0-alpha.3)

**Comment by madppiper** [comment]
I got the same problem. It seems that the html used on the demo differs quite a bit from the html generated by the github sources. Notable differences:

* "app" class in body
* Wrapping "app-body" div element around sidebar and main element
* heade class changed from "navbar" to "app-header navbar" 

and so on. There are also differences when it comes to the chart classes it seems. 

Anyway, during my own tests, the sidebar is displayed fine for desktop, but removed from mobile view. When adding the toggler element to the header, the toggler will display a 10px wide sidebar only. The mobile header is also screwed up, with elements overlapping (i was able to reproduce all of these things on the clean github sources, also, when i added the additional html elements to them).




I am using the static html version. Images attached

![desktop](https://cloud.githubusercontent.com/assets/6546292/23252400/fd91c2ca-f9b0-11e6-9b62-12cb52a676cf.png)


![mobile](https://cloud.githubusercontent.com/assets/6546292/23252405/01d4c828-f9b1-11e6-82c3-4dbb818654b9.png)

**Comment by clarkj** [comment]
Same issue appears on Angular 1 version, with the same details.  Anyone find a workaround?  I've noticed the _mobile.scss code is all commented out, and to put it back in is breaking.

**Comment by clarkj** [comment]
@iamonuwa @madppiper If you are still looking for a workaround, search for "@media (max-width: 991px)" in css/style.css.  I don't really have a use for a mobile version of the site, so I just removed that entire section of styling to keep the desktop view visible at any size, but a more detailed examination of the styles would almost definitely reveal the issue.  I also removed a lot of the hiding by size in the views/common/navbar.html file.  Hope this helps!

**Comment by hernanjh** [comment]
Hello, in Angular version, edit \js\directives.js

Replace
angular.element('body').toggleClass('mobile-open')
for
angular.element('body').toggleClass('sidebar-mobile-show')

**Comment by iamonuwa** [comment]
@hernanjh it works fine!!!

**Comment by srinivasanzdo** [comment]
@hernanjh thanks buddy, its working fine

**Comment by rotela** [comment]
@hernanjh thanks bro

**Comment by HosMercury** [comment]
for react add show / hide class to the side

**Comment by Venteri** [comment]
> for react add show / hide class to the side

what do you mean?

**Comment by gaurav-vij** [comment]
We are facing the exact same issue. I checked for the solution angular.element('body').toggleClass('sidebar-mobile-show'). But there is no js\directives.js file. Please address this with exact steps and changes.
