### ISSUE TITLE
Side menu height not expanding when dashboard content off screen

### ISSUE THREAD

**Issue by cnd5041** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#111]
If you have dashboard content that is taller than the screen area, the side menu does not scale high enough, so when you scroll, the side menu cuts off. 

I am using the v1.0.0-alpha.3 Angular CLI Starter version

![screen shot 2017-02-14 at 4 46 12 pm](https://cloud.githubusercontent.com/assets/8453414/22953080/410b62c8-f2d5-11e6-9b41-d305d897219c.png)

**Comment by mrholek** [comment]
Hi, I know about issue. I will fix it ASAP.
