### ISSUE TITLE
Vue vue-strap dependency issue

### ISSUE THREAD

**Issue by tjankov** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#123]
Im getting this when I run `npm run dev` :

```
This dependency was not found:

* vue-strap/src/modal in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/components/Modals.vue

```

(I've run npm install)

**Comment by socall92** [comment]
I have another issue on vue admin.
1) "npm install" run successfully.
2)"npm run dev", there is a error."Module build failed: Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'"

**Comment by tjankov** [comment]
Are you sure you are not using another version, socall92, the React one?
Instead of Vue?

**Comment by socall92** [comment]
I'm sure the working directory is Vue_Full_Project. I‘m surprise about the error is relate to react too.

**Comment by tjankov** [comment]
For my issue, I would love to try to solve it myself, but I wouldnt know where to start.
I dont think it is a serious issue, it is an unresolved dependency issue

**Comment by tjankov** [comment]
I have fixed the issue with Vue modal dependency in Vue Full Project, submitted pull request

**Comment by tjankov** [comment]
In Vue Full Project, in `src/views/components/Modals.vue`, there is a small letter
for modal dependency path on line 118.

Changed it to 
`import modal from 'vue-strap/src/Modal'`, now it works.

Issue can be closed if that is accepted.
