### ISSUE TITLE
Datatables not support ?

### ISSUE THREAD

**Issue by dhelazt** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#124]
I dont know if this bug or just because core-ui not supported datatables yet, but when i try to integrate datatables it seems the style is not worked like this.
![cap](https://cloud.githubusercontent.com/assets/12581988/23578687/b39b03de-0117-11e7-83fd-3b9bc7a40aab.PNG)

**Comment by iamjonmiller** [comment]
I edited the JS DOMto get Datatables.net's BS4 version to work with CoreUI. Replace the BS4 js file (https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap4.min.js) with this.


[Datatables Fixed for CoreUI.zip](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/files/842678/Datatables.Fixed.for.CoreUI.zip)

**Comment by dhelazt** [comment]
can you show your code? i've try and it seems work, except some border is missing and the table is not automatically resize.

**Comment by iamjonmiller** [comment]
No problem! I hope I helped

**Comment by oludouglas** [comment]
Was facing the same challenge and tried editing the datatable js file but in vain. thanks.

**Comment by pepepaco** [comment]
would not be better to modify CoreUI instead?
otherwise we would need to modify the file on every release. 
also DataTables could be integrated by default into the site.

**Comment by hosamshahin** [comment]
DataTables is supported only in CoreUI PRO.

**Comment by zxvdzx** [comment]
> I edited the JS DOM to get Datatables.net's BS4 version to work with CoreUI. Replace the BS4 js file (https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap4.min.js) with this.
> 
> [Datatables Fixed for CoreUI.zip](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/files/842678/Datatables.Fixed.for.CoreUI.zip)
> 
> Should look like:
> <img alt="2017-03-14 14_05_29-dashboard" width="840" src="https://cloud.githubusercontent.com/assets/21957977/23922384/5dab0a0a-08bf-11e7-8569-46309045cc82.png">

thanks brother, fixed for me.

**Comment by xx1196** [comment]
I could not implement datatables in core ui please someone help me

**Comment by vishalinfyom** [comment]
use https://github.com/InfyOmLabs/coreui-generator/

it has its own custom datatable 

![image](https://user-images.githubusercontent.com/33887755/66396796-209f9000-e9f8-11e9-95f6-113244dbb7d3.png)

**Comment by Kheyzel** [comment]
> I edited the JS DOM to get Datatables.net's BS4 version to work with CoreUI. Replace the BS4 js file (https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap4.min.js) with this.
> 
> [Datatables Fixed for CoreUI.zip](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/files/842678/Datatables.Fixed.for.CoreUI.zip)
> 
> Should look like: <img alt="2017-03-14 14_05_29-dashboard" width="840" src="https://cloud.githubusercontent.com/assets/21957977/23922384/5dab0a0a-08bf-11e7-8569-46309045cc82.png">

how to implement this? help me plsss
