### ISSUE TITLE
.dropdown-menu-right stuck open after selection

### ISSUE THREAD

**Issue by schlunix** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#130]
I'm trying to load content into the '$.mainContent' area from the 'dropdown-menu-right' links. The content loads fine, but the dropdown-menu-right menu is stuck open. The menu will not close no matter what else in the menu or on the screen is clicked. Attached screenshot might better explain the problem. Content is loaded just fine, but the menu is stuck open.
![screenshot from 2017-03-12 18-48-11](https://cloud.githubusercontent.com/assets/14342439/23837878/d4d948f6-0754-11e7-8ae5-2c3fcfea6256.png)

```
<div class="dropdown-menu dropdown-menu-right">
    <div class="dropdown-header text-center">
        <strong>Account</strong>
    </div>
    <a href="#" class="dropdown-item">
        <i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span>
    </a>
    <div class="dropdown-header text-center"><strong>Settings</strong>
    </div>
    <a href="#" class="dropdown-item"><i class="fa fa-user"></i> Profile</a>
    <a href="usersettings.html" class="dropdown-item"><i class="fa fa-wrench"></i> Settings</a>
</div>
```

**Comment by schlunix** [comment]
I should also note that if I manually navigate to hostname/#usersettings.html, the dropdown menu opens itself up with the "Settings" item selected.

**Comment by tjankov** [comment]
I think when you create an issue like this, you should specify in which variation of the CoreUI you have this isue.

**Comment by schlunix** [comment]
@tjankov, Absolutely, my apologies. 
Version is 1.0.0-alpha.4
Specifically the AJAX variant.

**Comment by mrholek** [comment]
I found where is problem. There is bug in app.js. I will fix it and upload new version
