### ISSUE TITLE
Left side menu not showing when hamburger icon clicked

### ISSUE THREAD

**Issue by shehan** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#132]
I encountered the following issue in Static_Full_Project_GULP & Angular_Full_Project_GULP

I resized the width of the browser so that the left side menu is automatically hidden. When I click on the hamburger icon, the left side menu is not shown.

Browsers: Chrome 56.0.2924.87 (64-bit) & Microsoft Edge 38.14393.0.0

**Comment by JairFrancesco** [comment]
This worked for me. (Angular_Full_Project_GULP)
inside directives.js I added in function layoutToggleDirective($interval)

if (element.hasClass('mobile-sidebar-toggler')){
        angular.element('body').toggleClass('sidebar-mobile-show');
}

So the function layoutToggleDirective  would be

//LayoutToggle
layoutToggleDirective.$inject = ['$interval'];
function layoutToggleDirective($interval) {
  var directive = {
    restrict: 'E',
    link: link
  }
  return directive;

  function link(scope, element, attrs) {
    element.on('click', function(){

      if (element.hasClass('mobile-sidebar-toggler')){
        angular.element('body').toggleClass('sidebar-mobile-show');
      }

      if (element.hasClass('sidebar-toggler')) {
        angular.element('body').toggleClass('sidebar-hidden');
      }

      if (element.hasClass('aside-menu-toggler')) {
        angular.element('body').toggleClass('aside-menu-hidden');
      }
    });
  }
}

**Comment by hrvylein** [comment]
@JairFrancesco thanks that solved it

**Comment by shehan** [comment]
Thanks @JairFrancesco ! I Incorporated your code and it worked.

**Comment by TiagoCunhaF** [comment]
Thanks!!!
