### ISSUE TITLE
Move angular-cli.json to .angular-cli.json

### ISSUE THREAD

**Issue by airborn** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#139]
`angular-cli.json` is now `.angular-cli.json` according to [wiki](https://github.com/angular/angular-cli/wiki/stories-1.0-update#angular-clijson)

I guess that this is something that can be done through `@angular/cli` and requires manual change. 

I guess that this would be required for both Angular2* and Angular4*

**Comment by mrholek** [comment]
I'm working on it
