### ISSUE TITLE
Angular 1 sidebar-nav breaks on resizing & mobile mode

### ISSUE THREAD

**Issue by clarkj** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#140]
The Angular CoreUI demo online and the template on GitHub behave differently.    Online, with the sidebar-nav open or closed, after sizing the page down below a certain threshold, the navbar converts to a mobile-friendly version, with no change to the state of the sidebar-nav, which remains toggleable.  After pulling a fresh copy of the Angular full demo and serving it, resizing the page with the sidebar-nav open results in the sidebar being closed and untoggable, and resizing the page with the sidebar closed results in a small piece of the sidebar-nav opening into the screen like so:

![breakingcoreui](https://cloud.githubusercontent.com/assets/19524058/24370177/4e16b686-12db-11e7-8656-338370569ff2.png)

This issue was also present in the version I pulled about a month ago.  I really appreciate all the work you've put into this.

**Comment by clarkj** [comment]
Closing in favor of #106

**Comment by hernanjh** [comment]
Hi, modify css/style.css

Replace

.sidebar-hidden .sidebar {
  margin-left: -200px; }

For

@media (min-width: 992px) {
.sidebar-hidden .sidebar {
  margin-left: -200px; }
}
