### ISSUE TITLE
[Vue] Laravel / Mix integration

### ISSUE THREAD

**Issue by Braunson** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#142]
Trying to use this in Laravel 5.4 with Laravel Mix, so far everything looks to be compiling minus some warnings, but for some reason when viewing the page I get these errors..

Note: I've tried with both the VueStarter and VueFull code.

```
[Vue warn]: Unknown custom element: <App> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
2017-03-31 18:50:52.405 app.js:1154[Vue warn]: Cannot find element: #app 
2017-03-31 18:50:52.406 app.js:1154[Vue warn]: Unknown custom element: <App> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in <Root>)
```

Thoughts?

**Edit:** I ended up [just manually merging it together](https://github.com/Braunson/laravel-coreui-vue) (not ideal) but it works. A more clean implementation from the author would be great _i.e. a Laravel Mix version_

**Comment by Wipsly** [comment]
Vue can't find a div of app. You need to define it. Like so:

<div id="app"></div>

**Comment by Braunson** [comment]
@Wipsly It was defined as a div like your example, I ended up getting around it, it was an issue with the Component.
