### ISSUE TITLE
Bootstrap spacer overrides default behavior

### ISSUE THREAD

**Issue by ArgTang** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#144]
Spacer override in _bootstrap-variables.scss changes the default bootstrap behavior. 
https://v4-alpha.getbootstrap.com/utilities/spacing/

Considering making the bootstrap defaults as is. 
Also this will break in next bootstrap update, as spacing have been refactored lately

**Comment by mrholek** [comment]
I'm working on it
