### ISSUE TITLE
when run "npm run ng serve" error

### ISSUE THREAD

**Issue by jiadongpo** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#152]
$ cnpm run ng serve
> CoreUI@1.0.0-alpha.4 ng D:\Workspaces\workspace_xxl\Angular2_CLI_Full_Project
> ng "serve"
** NG Live Development Server is running on http://localhost:4200 **
Hash: 81aaa6a79b197daaecae                                                      Time: 17110ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 212 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 45.3 kB {4} [initial] [rendered]
chunk    {2} scripts.bundle.js, scripts.bundle.js.map (scripts) 360 kB {5} [initial] [rendered]
chunk    {3} styles.bundle.js, styles.bundle.js.map (styles) 283 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.72 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'DropdownModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/Workspaces/workspace_xxl/Angular2_CLI_Full_Project/src/app/app.module.ts, resolving symbol AppModule in D:/Workspaces/workspace_xxl/Angular2_CLI_Full_Project/src/app/app.module.ts

ERROR in D:/Workspaces/workspace_xxl/Angular2_CLI_Full_Project/src/app/app.module.ts (6,10): Module '"D:/Workspaces/workspace_xxl/Angular2_CLI_Full_Project/node_modules/ng2-bootstrap/dropdown/index"' has no exported member 'DropdownModule'.)
webpack: Failed to compile.
ThinkPad@THINKPAD-PC MINGW64 /d/Workspaces/workspace_xxl/Angular2_CLI_Full_Project/src/app
$

**Comment by mrholek** [comment]
Please use Angular 4 Version instead of Angular 2

**Comment by jiadongpo** [comment]
Another version has been replaced, thank you very much for your reply！
