### ISSUE TITLE
Material Design Integration

### ISSUE THREAD

**Issue by caglarturkurka** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#160]
Hi, I want to ask a question about Core UI admin template. Please tell me how can we integration CORE UI admin template with material design component.Because some component of material design I want to use in my project.

Thank you

**Comment by RubanMaster** [comment]
+1

**Comment by ronesp86** [comment]
+1

**Comment by engAhmad** [comment]
I did this by importing the  MD  in shared model , but now i think it not good idea to mix 2 different frameworks having different concepts and concerns .
