### ISSUE TITLE
Dropdown position

### ISSUE THREAD

**Issue by tayzee** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#161]
LUKASZ HOLECZEK, thank you so much for this template, it has helped me so much in my recent journey into React.

Theres a small bug that I think i have found as per the screenshot attached. The dropdown for the item on the right is going off the page.

If the dropdown that you are opening is on the right edge, it should open to the left?!

Let me know what you think, otherwise I really love this theme! thank you!
<img width="1680" alt="screen shot 2017-04-27 at 23 22 51" src="https://cloud.githubusercontent.com/assets/6752666/25505437/f2783874-2ba1-11e7-9847-cc00892e4190.png">

**Comment by xidedix** [comment]
fixed
