### ISSUE TITLE
Sidebar-toggle is not working with Angular 4, Bootstrap 4

### ISSUE THREAD

**Issue by raff90** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#164]
I just updated my project to Angular 4, Bootstarp 4 with Angular CLI v 1.0, However, i notice that my sidebar not working. Please advice. 

```
<ul class="nav navbar-nav">
    <li class="nav-item">
        <button class="nav-link navbar-toggler sidebar-toggle hidden-md-down" >&#9776;</button>
    </li>

</ul>

```
```
<div class="sidebar">
<nav class="sidebar-nav">
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" routerLinkActive="active" [routerLink]="['/dashboard']"><i class="fa fa-
          tachometer"></i> Dashboard </a>
    </li>
</ul>
</nav>
</div>
```

**Comment by kolkov** [comment]
Worked for me
```
<button class="navbar-toggler  d-lg-none" type="button" appMobileSidebarToggler>&#9776;</button>
 <li class="nav-item">
      <a class="nav-link navbar-toggler" appSidebarToggler>&#9776;</a>
 </li>
```

**Comment by ezzkht** [comment]
@raff90  You're missing the "appSidebarToggler" / "appMobileSidebarToggler" class on the button.

**Comment by NabinKhatiwada** [comment]
For me It worked like this:

<nav>
    <button class="navbar-toggler mobile-sidebar-toggler hidden-lg-up" type="button">&#9776;</button>
    <ul class="nav navbar-nav">
        <li class="nav-item">
            <button  class="nav-link navbar-toggler sidebar-toggler hidden-md-down"  href="#">&#9776;</button>
        </li>
    </ul>
</nav>
