### ISSUE TITLE
missing files?

### ISSUE THREAD

**Issue by tknman0700** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#167]
When I look at the static demo there are files missing from browser_components - thanks

**Comment by klasker** [comment]
You need to use bower to download the dependencies from the bower.json file.

**Comment by hickhub** [comment]
Ajax - no bower.json file.

**Comment by mrholek** [comment]
We don't use bower.

**Comment by hickhub** [comment]
On this page http://coreui.io/docs/getting-started/ajax-version/ it says to install bower
