### ISSUE TITLE
Problem with checkmark outline icon inside Switches

### ISSUE THREAD

**Issue by johnlee** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#168]
I'm finding a problem with the Switches. When I try to create one with the checkbox icon inside, the icons are not displaying correct. On the demo site, I'm referring to the "Switch with icon"

http://coreui.io/demo/Angular_Demo/#/components/switches

The HTML looks like so:
`          <label class="switch switch-icon switch-pill switch-info-outline-alt">
            <input type="checkbox" class="switch-input" checked>
            <span class="switch-label" data-on="#xf00c" data-off="#xf00d"></span>
            <span class="switch-handle"></span>
          </label>`

With this the checkmark doesnt display and instead shows "#xf00c". If I change the switch-label to the following, the checkmark then correctly appears. I'm not sure what this special character difference is though. Could I get an explanation on this?
`          <label class="switch switch-icon switch-pill switch-info-outline-alt">
            <input type="checkbox" class="switch-input" checked>
            <span class="switch-label" data-on="" data-off=""></span>
            <span class="switch-handle"></span>
          </label>
`

**Comment by xidedix** [comment]
fixed
