### ISSUE TITLE
Error while doing npm install

### ISSUE THREAD

**Issue by Synster** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#18]
error node v5.0.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error CoreUI@1.0.0-alpha.1 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 1
23 error Failed at the CoreUI@1.0.0-alpha.1 start script 'tsc && concurrently "tsc -w" "lite-server" '.

**Comment by mrholek** [comment]
Hi, I'm working on it.

**Comment by mrholek** [comment]
I fixed it, please download latest version.
