### ISSUE TITLE
Vue Starter template not responsive.

### ISSUE THREAD

**Issue by Eduardoveras** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#181]
The Vue full proyect is responsive, but the starter proyect is not responsive, something seems to be missing

**Comment by moJiXiang** [comment]
Add '  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
' to index.html.

**Comment by Eduardoveras** [comment]
Thank you, should be added by default, will make a PR later to add it

**Comment by Eduardoveras** [comment]
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/pull/191
