### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by HaHaHaHaHaHaHaaaaaa** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#182]
$('#myModal).on('shown.bs.moal',(e)=>{

})

i have imported jquery, it still doesn't work,why?

**Comment by brunoseco** [comment]
shown.bs.moal it is shown.bs.**modal**

**Comment by cassianomon** [comment]
Close this issue please @HaHaHaHaHaHaHaaaaaa
