### ISSUE TITLE
Upgrade Bootstrap version to beta

### ISSUE THREAD

**Issue by mrholek** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#196]

**Comment by Qrzysio** [comment]
Bootstrap 4 beta is out. would nice to see updated CoreUI as BT4 provides new clasess and some changes.

**Comment by dushkostanoeski** [comment]
I'd like to help, split the workload, speed things up 👍

**Comment by mrholek** [comment]
Hi new version should be ready on Monday
