### ISSUE TITLE
Vuejs on IE11

### ISSUE THREAD

**Issue by Jlabarca** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#203]
Someone knows how to get vuejs version working on Internet explorer 11

Even [Vuejs example](http://coreui.io/demo/Vue_Demo/#/ ) get an error.
I know it's  because promises and the solution have something to do with polyfill, but I tried several things and nothing works.

In my project I get **Syntax Error** on app.js
And in Vue_Demo it is on vendor.xxx.js 

Thanks

**Comment by marktolson** [comment]
I'm getting this error on IE11 as well. Even when I wrap the app.vue template in a script tag I end up with errors in app.js (in debug). Any help with this?

**Comment by marktolson** [comment]
@Jlabarca I only got around this issue by rebuilding the whole thing from the ground up using vue-cli, adding the webpack template, then adding dependencies (vue-chartjs, vue-strap etc) then adding the styles and views back in.

**Comment by xidedix** [comment]
Current Vue version of CoreUI has been moved to [https://github.com/mrholek/CoreUI-Vue](https://github.com/mrholek/CoreUI-Vue)
