### ISSUE TITLE
React project not watching scss file changes cohesively

### ISSUE THREAD

**Issue by connectdotz** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#208]
The react project document indicated to use `npm start` (which basically run the react-scripts) to start the server, which compiles and watches js file. The current configuration setup seems to rely on gulp to compile and watch scss with `gulp sass` and `gulp sass:watch`, several problems with this approach:
1. it is not clearly indicated in the react project document 
1. while gulp watcher did recompile the scss files upon change, it doesn't notify the react-scripts to refresh the browser

Seems to me that either migrate the react project to adopt webpack as the scss watcher, which is the official scss handling in the facebook doc; or somehow integrate the gulp with react-scripts to start gulp watcher and trigger auto refresh upon scss change...

thoughts?

**Comment by mrholek** [comment]
Fixed in latest release
