### ISSUE TITLE
Fixed position for Breadcrumb

### ISSUE THREAD

**Issue by dacodekid** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#213]
Would it be possible to add a `breadcrumb-fixed` class as other fixed components (`navbar`, `sidebar`, `footer`)?

**Comment by mrholek** [comment]
No, this isn't possible at the moment.

**Comment by gpolyn** [comment]
@mrholek how can additional fixed position components be _stacked_ below a `fixed-top` element, such as `navbar`? Likewise, how can additional fixed components be stacked above a `fixed-bottom` element, such as `footer`?

**Comment by dacodekid** [comment]
If you have both `sidebar` & `aside-menu` be `off-canvas` and `hidden`...., which in my case - this css works for me (add the `breadcrumb-push` class to the main div below `breadcrumb`.

```html

<body class="app header-fixed sidebar-hidden sidebar-off-canvas aside-menu-off-canvas aside-menu-hidden">

  ...

  <main class="main">
    <!-- Breadcrumb -->
    <nav class="breadcrumb breadcrumb-fixed">
      <div class="float-left pt-1">
        <span class="breadcrumb-item font-weight-bold">
        </span>
      </div>
      <div class="float-right">
      </div>
    </nav>

    <div class="container-fluid breadcrumb-push">
    </div>
  </main>
```

```css
.breadcrumb-fixed {
  position: fixed;
  z-index: 2;
  width: 100%;
}

.breadcrumb-push {
  margin-top: 5em;
}
```

**Comment by gpolyn** [comment]
@dacodekid hey that works great, thanks a lot!

**Comment by mrholek** [comment]
We will add this feature in next release.

**Comment by aakashjain** [comment]
@dacodekid I've actually found that you don't need `sidebar` & `aside-menu` be `off-canvas` and `hidden`. In my case, I had `header-fixed sidebar-fixed aside-menu-hidden` and your solution worked perfectly.

Also, your solution could be made a bit more concise and consistent with CoreUI's conventions as follows:

```
<body class="app header-fixed sidebar-fixed aside-menu-hidden breadcrumb-fixed">
// no need to add any classes to the breadcrumb or the container
```
```
.breadcrumb-fixed .breadcrumb {
  position: fixed;
  z-index: 1010;
  width: 100%;
}
.breadcrumb-fixed .container-fluid {
  margin-top: 5 * $spacer;
}
```

**Comment by dacodekid** [comment]
@aakashjain , it may seem work with `sidebar-fixed` but since it's `position: fixed`, the `width: 100%' will push the container to the right.  Plz try to place some components on the right side of `breadcrumb` and you'll see what I mean.

**Comment by gpolyn** [comment]
Silly question: why would any of the template's fixed elements -- `header`, `footer` or `breadcrumb` -- need to have a `z-index` or  `fixed `position? Shouldn't the scrolling content be nested inside a container that contains optionally one or more of the fixed elements? (Related: [issue 225](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/issues/225).)
