### ISSUE TITLE
Please provide Alba template as a single _custom-variables.scss file, instead of a full repo

### ISSUE THREAD

**Issue by mariusa** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#233]
Rather than maintaining separate repos for different themes, would you please provide Alba template as a single _custom-variables.scss file, that works on top of CoreUI?
https://github.com/mrholek/Alba-Bootstrap-4-Admin-Template/tree/master/Vue_Full_Project/scss

Thank you!

**Comment by mrholek** [comment]
Alba is Premium Admin Template and have more components then CoreUI.
