### ISSUE TITLE
Nothing is clickable once a modal is open

### ISSUE THREAD

**Issue by dushkostanoeski** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#235]
Built the Angular 4 full project and opened a modal, couldn't click anywhere afterwards

**Comment by dushkostanoeski** [comment]
Just figured out that if you backwards in the order that the modals are placed in the HTML, the modals work, but if you skip one, then you won't be able to close the one that's open.

**Comment by iamjonmiller** [comment]
+1 I have two for loops, one that creates a button to launch a modal for each unique id and another that creates modals for each unique id. I though I had done something wrong, but if I start from the last one they all work.

**Comment by kitloong** [comment]
Hi,

I able fixed this issue by comment out line 31 in scss/core/_temp.scss
```
/*.modal-open .modal {
  display: block;
}*/

**Comment by 3ncor3** [comment]
@kitloong solution work for me. Thanks.
