### ISSUE TITLE
When we minimize browser small, left menu not work in Angular2 version

### ISSUE THREAD

**Issue by mrholek** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#24]

**Comment by jackyphuong** [comment]
Thanks, please let me know when it is fixed

**Comment by jackyphuong** [comment]
Hello, did u fix yet? Could u please share me code changes to fix it ?

Thanks,

**Comment by mrholek** [comment]
Please copy and paste following files to your project:

Angular2_Dev/app/shared/sidebar.directive.js
Angular2_Dev/app/shared/sidebar.directive.js.map
Angular2_Dev/app/shared/sidebar.directive.ts

and then go Angular2_Dev/app/layouts/full-layout.component.html and change following code 

`<button class="navbar-toggler hidden-lg-up" type="button">&#9776;</button>`

to this

`<button class="navbar-toggler hidden-lg-up" type="button" mobile-nav-toggle>&#9776;</button>`

**Comment by jackyphuong** [comment]
thanks, confirmed
