### ISSUE TITLE
psd files for designers

### ISSUE THREAD

**Issue by SLRXXX** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#247]
Could you please provide a set of psd files for groups that need designs before development?
Or is there any other alternative solutions?

**Comment by mrholek** [comment]
We're working on sketch files. It should be available soon

**Comment by Davst** [comment]
@mrholek Any update on "Soon™️"?

**Comment by mrholek** [comment]
Hi at this moment we don't have enough resources to create sketch files. We have to hire someone to do this.

**Comment by cocowalla** [comment]
@mrholek would you consider trying something like Bountysource to fund it as OSS, or would the intention be to hire someone and only have the PSD/Sketch files available to commercial license users?

**Comment by hammashamzah** [comment]
Any update for this?
