### ISSUE TITLE
ActionView::Template::Error (Base-level rules cannot contain the parent-selector-referencing character '&'.):

### ISSUE THREAD

**Issue by stopanko** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#249]
This commit have broke scss compiling for rails static template. [d104609bafafd68ab4a4856cac73e50f98ace2e9](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/commit/d104609bafafd68ab4a4856cac73e50f98ace2e9)

`ActionView::Template::Error (Base-level rules cannot contain the parent-selector-referencing character '&'.):`
The problem in `@import "core/core";` file(or in one of required inside) that required in `style.scss`

**Comment by daveio** [comment]
bump, PR #287 submitted.
