### ISSUE TITLE
Elements Sizes Extra Small and Small

### ISSUE THREAD

**Issue by peio72** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#25]
It seems there are issues with Extra Small Size for buttons: .btn-xs, and also the Select and Input Small elements.
Their size is the same as normal elements.

**Comment by peio72** [comment]
Any chance it could be fixed ?

**Comment by mrholek** [comment]
Bootstrap 4 doesn't support .btn-xs, so I decided to remove it.

**Comment by nj** [comment]
@mrholek FYI it still appears [on the demo site](http://coreui.io/demo/Ajax_Demo/#components/buttons.html) :wink:

Seems to be the entire demo all-in-all, using an older version (including bootstrap v4.0.0-alpha.3, CoreUI v1.4.2 from 2016 making it a different version branch).
