### ISSUE TITLE
Icons not working with Switches

### ISSUE THREAD

**Issue by snarlynarwhal** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#259]
I see the html entity number instead of the actual icon. Even in the [Switch docs](http://coreui.io/docs/new-components/switches/#switch-with-icon) it appears to not work.

**Comment by xidedix** [comment]
Which version?

**Comment by snarlynarwhal** [comment]
Ok so the docs show:

![image](https://user-images.githubusercontent.com/3300071/29981198-d0514556-8f1a-11e7-92ad-38f027a2bc08.png)

I figured out that it needs a `;` at the end. Adding that fixed it for my project. I even inspected element on the Switch docs page and added the `;` and it instantly worked:

![image](https://user-images.githubusercontent.com/3300071/29981249-02b3b420-8f1b-11e7-99af-9addbc7d2dea.png)

**Comment by xidedix** [comment]
the issue is addressed already, please find current source here 
https://github.com/mrholek/CoreUI-Angular

**Comment by snarlynarwhal** [comment]
Oops I completely neglected to answer:

> Which version?

My bad! I'm using React Starter, but I assume the issue has been addressed in all versions?

Thanks for the help!
