### ISSUE TITLE
Bootstrap beta

### ISSUE THREAD

**Issue by randinterval** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#263]
Hi,
Are there any plans to migrate this over to bootstrap v4 beta?

**Comment by Wachert** [comment]
I already use it with BS4 Beta and it works fine, what do you mean what needs to be migrated?

**Comment by xidedix** [comment]
React version of CoreUI relies on Reactstrap v4.8 components, based on bootstrap@4.0.0-alpha.6 
We are going to migrate to Reactstrap v5 (bootstrap@4.0.0-beta) when ready.

**Comment by randinterval** [comment]
@xidedix Thank you! What are the plans for Angular version?

**Comment by korn3l** [comment]
@randinterval As far as I know the Angular version is already using bootstrap 4 beta

**Comment by randinterval** [comment]
@korn3l Thanks!
