### ISSUE TITLE
What's the difference between each version(Html5、html5 ajax、angular、react.js、vue.js) ?

### ISSUE THREAD

**Issue by leafonsword** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#264]
Hi, I'm a newbie to Html、CSS、JS，I'm learning Html5、CSS3 and JS; I have some confusion about each version: I knew angular、react、vue are js frameworks，so these versions are same catalog, but what's the difference with html5、ajax and vue？ My first compression is that: 
1. Html5 version is just static, didn't contain js, so couldn't act with server
2. Html5 and ajax version uses js to act with server
3.Angular、react、vue these versions use js frameworks to act with server, and they use html 4

Is my comprehend right? If so, to me a newbie, and I also want to act with server, maybe Html5 ajax version is easier  and a better choose?

**Comment by mrholek** [comment]
You're right. Ajax version will be the best for you.
