### ISSUE TITLE
node module class name problem of ng2-chart.

### ISSUE THREAD

**Issue by sorieil** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#27]
When i run "npm start"

The error occurs as follow.

app/app.module.ts(8,10): error TS2305: Module '"/Users/[account]/CoreUI-Free-Bootstrap-Admin-Template/Angular2_Dev/node_modules/ng2-charts/ng2-charts"' has no exported member 'CHART_DIRECTIVES'.

So i solved the problem that changed CHART_DIRECTIVES to ChartsModule.

**Comment by mrholek** [comment]
thank you for your feedback. I fixed this issue in latest version.
