### ISSUE TITLE
Cant interact with modals

### ISSUE THREAD

**Issue by idtareq2** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#271]
when having multiple modals with the slide or fade animation, i cant interact with the modals (like click a button)
the problem is also present here http://coreui.io/docs/components/modal/

**Comment by idtareq2** [comment]
this is what worked
`
$('#Modal').on('show.bs.modal', function (event) {
	$(this).css("z-index", "2000");
});
$('#Modal').on('hide.bs.modal', function (event) {
	$(this).css("z-index", "");
});
`

**Comment by cyberfly** [comment]
I have the same problem? How do you solve this one?
