### ISSUE TITLE
Dropdown in card-header

### ISSUE THREAD

**Issue by carxl** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#296]
Hi, this is not a issue, is about a doubt.

By default can i put a dropdown menu in card-header? I was looking for in your docs but only found this:

<img width="1146" alt="screenshot 2017-11-08 11 31 08" src="https://user-images.githubusercontent.com/2106601/32560713-5c5ac850-c478-11e7-9367-e25fe79bfe75.png">

The idea is a dropdown menu in that position like the uploaded image. Is it possible with your default CSS? Or i must to build a custom CSS?

Thanks in advance.

**Comment by bellwood** [comment]
Works just fine - add the following markup to the card-header and edit as needed

```
<div class="card-actions">
                <a href="#" class="btn-setting"><i class="icon-settings"></i></a>
                <a href="#" class="btn-minimize"><i class="icon-arrow-up"></i></a>
                <a href="#" class="btn-close"><i class="icon-close"></i></a>
</div>
```

**Comment by bellwood** [comment]
It's also worth mentioning that app.js has markup specific to the behavior of anchors in that menu.

If your intention is to simply have them be anchors, then you can remove the markup in app.js - otherwise you'll need to alter it to suite your needs.

**Comment by carxl** [comment]
Thanks for ur answer @bellwood. This is my code put in card-header div and works fine!

```html
<a href="#" class="btn pull-right dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="icon-settings"></i></a>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="#" class="dropdown-item">Link 1</a>
            <a href="#" class="dropdown-item">Link 1</a>
            <a href="#" class="dropdown-item">Link 1</a>
          </div>
```

**Comment by bellwood** [comment]
Glad to help - feel free to close your issue if you are all set =)

**Comment by carxl** [comment]
Sure! Thank u!
