### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by terndrup** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#299]
Hey, 

first off, CoreUI looks like a great template, well done!

I am thinking of using it in a commercial product but I'm a little bit confused about the licensing of CoreUI. The license file included with the project is a standard MIT license in which it clearly says that we can distribute the software, in the Readme however it says:

```
copyright 2017 creativeLabs Łukasz Holeczek. The code is released under the MIT license. creativeLabs Łukasz Holeczek reserves the right to change the license of future releases.

You can’t re-distribute the CoreUI as stock. You can’t do this if you modify the CoreUI.
```
So there it says I cannot redistribute it as stock, which is fine, but also that I cannot redistribute it if I make changes? So if I incorporate CoreUI into my commercial product can I redistribute it? What if I need to change some things?

Can anyone explain this licensing a bit? Eager to get started using CoreUI!

Gracias,

**Comment by mrholek** [comment]
> You can’t re-distribute the CoreUI as stock. You can’t do this if you modify the CoreUI.

It means that you can use our template in commercial project and redistribute it, but you can't build admin template and sell it on marketplaces ex. themeforest and wrapbootstrap.

We had some problems with people who tried to sell our template on themeforest, that's why we added this terms.

**Comment by jilvin** [comment]
Kudos on the effort creating this wonderful work!

Though, it would be better if you could clarify the terms on the license in the LICENSE file itself.

**Comment by cocowalla** [comment]
+1 this does seem to run against the terms of the MIT license.

Honestly, I think if you actually have a problem with people building new themes on top of CoreUI (it would be nice if you permitted this though, and overall I think it would be good for CoreUI, with improvements being pushed back to upstream from forks), then you should choose an appropriate license - MIT isn't it. One of the Creative Commons licenses would most likely work better for you.

**Comment by ronkun** [comment]
Can you clear things up @mrholek 

Extended License means, that the template "CoreUI" can be used for a product (lets name it WebApp X) to build WebApp X which includes a lot of other programming parts from our side. If we wnt to sell this WebApp X now, we have to buy an extended license for every WebApp X sold??

Membership means, that we can sell WebApp X as often as we want? What happens with the previously sold products, if we end the Membership lets say in 5 years? 

Thanks in advance 
R

**Comment by ftntming** [comment]
> > You can’t re-distribute the CoreUI as stock. You can’t do this if you modify the CoreUI.
> 
> It means that you can use our template in commercial project and redistribute it, but you can't build admin template and sell it on marketplaces ex. themeforest and wrapbootstrap.
> 
> We had some problems with people who tried to sell our template on themeforest, that's why we added this terms.

You're Awesome!!

**Comment by nsrikanthgithub** [comment]
> Hello,
> 
> If I am developing a (Saas) app that customers will be paying to use, and I want to use Core UI to build the UI/UX for the App.
> I am using the free admin template as the base to create my App's UI.
> 
> Can I do this without any Licensing issues?

@nabeelh21  can we use free react admin template as base for your situation, You got any clarity on that ?

**Comment by JudeAshan98** [comment]
Hello,
If I use the CoreUI Free version and create a project for one of my customers. Is there is any commercialization or license issues?
