### ISSUE TITLE
Form validation classes not working

### ISSUE THREAD

**Issue by dyhaz** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#300]
Input classes for validations is not working in Angular2 demo: http://coreui.io/demo/Angular2_Demo/#/components/forms

![image](https://user-images.githubusercontent.com/4188531/32877708-6d44f4de-cad5-11e7-93e4-b4b79a384c7b.png)

**Comment by xidedix** [comment]
demo version has been updated:
[https://coreui.io/demo/Angular_Demo/](https://coreui.io/demo/Angular_Demo/)
