### ISSUE TITLE
node_modules folder notfound

### ISSUE THREAD

**Issue by temperory** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#304]
![2017-11-26_11-08-17](https://user-images.githubusercontent.com/3518570/33238067-47f1924c-d29a-11e7-82b4-f05e15eec984.jpg)

**Comment by bellwood** [comment]
Did you run `npm install` inside the CoreUI project you selected?

**Comment by marios-zindilis** [comment]
I also don't quite understand how to get all `node_modules` quickly. The `packages.json` file does not specify the dependencies, so an `npm install` run only creates an empty `node_modules` directory.

**Comment by bellwood** [comment]
`gulp serve` will build the rest of the project dependancies.

**Comment by suleodu** [comment]
run `npm install` that should do the magic
