### ISSUE TITLE
Update to Bootstrap Beta 3

### ISSUE THREAD

**Issue by ccoltman** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#316]
Is someone maintaining this still? I haven't seen any activity since November. I'm just wondering if I should Fork it and do these updates manually in the interim.

**Comment by mrholek** [comment]
We will update Bootstrap version ASAP.

**Comment by ccoltman** [comment]
Excellent thank you.

**Comment by ccoltman** [comment]
Bootstrap 4.0.0 is finally released!
