### ISSUE TITLE
Buttons stop working in 1.0.8

### ISSUE THREAD

**Issue by ccoltman** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#321]
Previously working buttons stopped functioning after upgrading to 1.0.8. 
For example we have a simple login form with a `<button type="submit">Login</button>` style interface which no longer submits the form. It looks like something is probably widely preventingDefault() but haven't had a chance to track it down yet.

**Comment by ccoltman** [comment]
Still broken, I'm using Static Full Project as a base btw.

**Comment by xidedix** [comment]
@ccoltman please try again

**Comment by ccoltman** [comment]
Button works again.
