### ISSUE TITLE
coreui.io is out of date

### ISSUE THREAD

**Issue by ccoltman** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#331]
Shouldn't the main demo (http://coreui.io/demo/Ajax_Demo/#main.html) site always have the latest version of the template live? It's still running 1.0.2.

I see the PRO version (http://coreui.io/demo/pro/Ajax_Demo/#main.html) is updated to 1.0.8, which is kind of backwards considering the main demo is supposed to be the base right? After all, it's the one we all contribute to.

**Comment by xidedix** [comment]
thanks @ccoltman 
demo version has been updated `1.0.2` -> `1.0.9`
