### ISSUE TITLE
Bootstrap v.4.x

### ISSUE THREAD

**Issue by kurumpa** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#336]
input-group-addon class has changed in Bootstrap release: https://getbootstrap.com/docs/4.0/migration/#input-groups

**Comment by DaniVarga** [comment]
I think this is already fixed but not published to npm.

**Comment by kurumpa** [comment]
Sorry, my bad, i should be more specific. I meant things like https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/search?utf8=%E2%9C%93&q=input-group-addon&type= 
This issue (and maybe a few more similar ones) should also be fixed on reactstrap's side, i'll notify the maintainer.

**Comment by xidedix** [comment]
Hi @kurumpa 
[React](https://github.com/mrholek/CoreUI-React), [Angular](https://github.com/mrholek/CoreUI-Angular), [AngularJS](https://github.com/mrholek/CoreUI-AngularJS) & [Vue ](https://github.com/mrholek/CoreUI-Vue) version of CoreUI has been moved to separate repos.
