### ISSUE TITLE
All modals in the doc are broken?

### ISSUE THREAD

**Issue by nicolasblanco** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#35]
Hello,

directly on the docs here:
http://coreui.io/docs/components/modal

When I click on any demo of a modal, the modal appears with a gray overlay on the full screen making it impossible to click anywhere.

Tried on: Safari 9 and Chrome 53 on MacOS X.

Thanks.
<img width="1351" alt="screen shot 2016-09-23 at 15 42 37" src="https://cloud.githubusercontent.com/assets/12682/18787744/6adc1edc-81a4-11e6-9aad-cc0cfe64788c.png">

**Comment by FacundoGFlores** [comment]
Same for Chrome 53 on Windows 10.

**Comment by joaodfmota** [comment]
Put modal at end of doc.

<div id="myModal">
...
</div>
</body>

**Comment by iamjonmiller** [comment]
If using Flask Templates, create a separate Jinja2 block for your modals and put it right before `</body>` as described above. 

```
{% extends "header.html" %}

{% block page_title %}Demo{% endblock %}

{% block content %}
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Open Modal
    </button>
{% endblock %}

{% block modals %}
<!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                        <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}
```

**Comment by dhelazt** [comment]
trying different solution, but only put the modal at the end fix the problem. I hope there is another solution for this, because some in some situation we cant put the modal at the end.

**Comment by andreujuanc** [comment]
For now I just did this: https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/issues/110
:( 
Dont have much time to check where the problem comes from. But yea, I agree that it's something that should be fixed.

**Comment by stefanocurnis** [comment]
Problem is in in .fadeIn class.
Removing it from the wrapping div solves the problem

**Comment by kobaltz** [comment]
Modifying the CSS ~line 5927 to look like this worked for me.

```@-webkit-keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
@-moz-keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
@-o-keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
@keyframes fadeIn {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}

.fadeIn {
  -webkit-animation: fadeIn; /* Safari 4+ */
  -moz-animation:    fadeIn; /* Fx 5+ */
  -o-animation:      fadeIn; /* Opera 12+ */
  animation:         fadeIn; /* IE 10+, Fx 29+ */
}```

**Comment by andreujuanc** [comment]
@kobaltz And you still getting the fadein animation, maybe PR it?  I'll make some tests.

**Comment by kobaltz** [comment]
@andreujuanc The `fadeIn` animations do still work with the changes.
![2017-05-30_12-22-21](https://cloud.githubusercontent.com/assets/635114/26593594/b9d5cea0-4532-11e7-982c-2d8007b9745a.gif)

**Comment by mlau7** [comment]
I had to take this code from the bootstrap.min.css and replace the coreUI CSS code. I also made the @kobaltz change up above to the fadeIn.

Fade code is ~line 2121
```
fade {
   opacity:0;
   -webkit-transition:opacity .15s linear;
   -o-transition:opacity .15s linear;
   transition:opacity .15s linear}
   .fade.in{opacity:1}
```

The same thing with the modal-backdrop, ~line 3526
```
.modal-backdrop{
  position:fixed;
  top:0;
  right:0;
  bottom:0;
  left:0;
  z-index:1040;
  background-color:#000}
  .modal-backdrop.fade {
    filter:alpha(opacity=0);
    opacity:0}
  .modal-backdrop.in {
    filter:alpha(opacity=50);
    opacity:.5}
```

**Comment by dipalinandecha** [comment]
try this
    <div bsModal #MyModal="bs-modal" class="modal fade"   tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" [config]="{backdrop: false}" >
