### ISSUE TITLE
How can i edit the sidebar items, add my own links and pages to it?

### ISSUE THREAD

**Issue by miki996** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#354]
Hi, 

How can i edit the sidebar items, add my own links and pages to it?

As i was going through the Sidebar.Vue and other Sidebar components i have no idea how can i customize the links, or add my own.

If you have some clue on this point your answer will be much appreciated.

**Comment by Narthe** [comment]
Hi @miki996, did you find how to do it ? I'm a total Vuejs newbie, i guess i shouldn't start with coreui project to learn but if you have any hint, i'll take it !
