### ISSUE TITLE
How  do I compile Angular2_Dev by gulp?

### ISSUE THREAD

**Issue by newkey20** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#36]
I don't see the Build Task in the Gulpfile, that's normal?

**Comment by mrholek** [comment]
I'm working on it. I will add gulp file ASAP

**Comment by newkey20** [comment]
Hey thanks,  I tried a little bit with gulp, but my knowledge is not enough yet

**Comment by ArmanFazylov** [comment]
Any updates on this issue?

**Comment by newkey20** [comment]
The build task in Angular2_Dev still an issue, I think

**Comment by pohlmannFrank** [comment]
Any updates on this issue?

**Comment by mrholek** [comment]
We decided to move Angular2 Version to angular-cli.
