### ISSUE TITLE
Duplicated Angular2_CLI_Dev SCSS folders?

### ISSUE THREAD

**Issue by esistgut** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#37]
Angular2_CLI_Dev/scss and Angular2_CLI_Dev/src/scss contain duplicated file and folders, is there a reason for this?

**Comment by esistgut** [comment]
And why aren't you building the styles from the SCSS files? The theme is including a precompiled .css file from the index.html, why aren't you including the required scss files in the styles section of the angular-cli.json file and setting the styleExt to scss?

**Comment by mrholek** [comment]
Hi I removed duplicated SCSS folders.

**Comment by esistgut** [comment]
I still see duplicated content but I don't really understand if there is a reason for this. Example:
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/tree/master/Angular2_CLI_Dev/scss/bootstrap_src
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/tree/master/Angular2_CLI_Dev/src/scss/bootstrap

**Comment by esistgut** [comment]
Ok, no more duplicated SCSS folders now. Can I ask if you plan to use angular-cli.json to automatically build the SCSS files to CSS ?

**Comment by mrholek** [comment]
Yes I'm going to add SCSS styles to angular-cli.json
