### ISSUE TITLE
Multiple select issue

### ISSUE THREAD

**Issue by FacundoGFlores** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#39]
Is multiple select broken?

![multiple](https://cloud.githubusercontent.com/assets/5167196/18992596/95ba21ac-86f5-11e6-8f49-2692fe2d121b.png)

I watched it in Angular2_Dev running it locally, but also in the web's examples.

**Comment by mrholek** [comment]
Will be fixed in next version
