### ISSUE TITLE
Clean up javascript

### ISSUE THREAD

**Issue by rwhitmire** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#4]
I was originally going to leave a comment on HN, but figured it might be more constructive to post here.

My primary complaint about most bootstrap themes is that the javascript quality tends to be rather low and it sometimes leads to subtle bugs that are very frustrating to track down. Global functions and variables polluting window is probably the most common issue I find.

https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L42
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L66
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L68
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L112
https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L117

Additionally, why pollute the $ namespace with constant values? These can easily be plain variables.

https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template/blob/master/dist/Static_Seed/assets/js/app.js#L8

All javascript should be wrapped in a closure, `'use strict';` should be included in the closure, and `var` should always be used when declaring variables.

**Comment by mrholek** [comment]
Thank you for your feedback, I will try to improve this.
