### ISSUE TITLE
Getting Error with RouterLink

### ISSUE THREAD

**Issue by anupamarachuri** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#41]
Hi Team,

I am trying to integrate this Project with Maven  build and I have included all the Node Modules mentioned too. Getting the below error. Please help

zone.js:355 Unhandled Promise rejection: Template parse errors:
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("v"> 
    <ul class="nav"> 
     <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/dashboard']"><i class="icon-speedometer"></i> Dashboard <span class="tag tag-info">N"): FullLayoutComponent@44:73
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/buttons']"><i class="icon-puzzle"></i> Buttons</a> </li> 
       <li clas"): FullLayoutComponent@49:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("></i> Buttons</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/social-buttons']"><i class="icon-puzzle"></i> Social Buttons</a> </li> 
 "): FullLayoutComponent@50:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("ocial Buttons</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/cards']"><i class="icon-puzzle"></i> Cards</a> </li> 
       <li class="n"): FullLayoutComponent@51:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("e"></i> Cards</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/forms']"><i class="icon-puzzle"></i> Forms</a> </li> 
       <li class="n"): FullLayoutComponent@52:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("e"></i> Forms</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/switches']"><i class="icon-puzzle"></i> Switches</a> </li> 
       <li cl"): FullLayoutComponent@53:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("</i> Switches</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/tables']"><i class="icon-puzzle"></i> Tables</a> </li> 
      </ul> </li>"): FullLayoutComponent@54:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/icons/font-awesome']"><i class="icon-star"></i> Font Awesome</a> </li> 
       <li c"): FullLayoutComponent@58:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. (" Font Awesome</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/icons/simple-line-icons']"><i class="icon-star"></i> Simple Line Icons</a> </li> 
  "): FullLayoutComponent@59:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. (" </li> 
      </ul> </li> 
     <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/widgets']"><i class="icon-calculator"></i> Widgets <span class="tag tag-info">NEW</s"): FullLayoutComponent@61:73
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/login']"><i class="icon-star"></i> Login</a> </li> 
       <li class="nav-item"): FullLayoutComponent@66:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("r"></i> Login</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/register']"><i class="icon-star"></i> Register</a> </li> 
       <li class="na"): FullLayoutComponent@67:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("</i> Register</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/404']"><i class="icon-star"></i> Error 404</a> </li> 
       <li class="nav-it"): FullLayoutComponent@68:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("/i> Error 404</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/500']"><i class="icon-star"></i> Error 500</a> </li> 
      </ul> </li> 
    <"): FullLayoutComponent@69:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("ss="btn btn-secondary" href="#"><i class="icon-speech"></i></a> 
      <a class="btn btn-secondary" [ERROR ->][routerlink]="['/dashboard']"><i class="icon-graph"></i> &nbsp;Dashboard</a> 
      <a class="btn btn"): FullLayoutComponent@83:35 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("v"> 
    <ul class="nav"> 
     <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/dashboard']"><i class="icon-speedometer"></i> Dashboard <span class="tag tag-info">N"): FullLayoutComponent@44:73
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/buttons']"><i class="icon-puzzle"></i> Buttons</a> </li> 
       <li clas"): FullLayoutComponent@49:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("></i> Buttons</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/social-buttons']"><i class="icon-puzzle"></i> Social Buttons</a> </li> 
 "): FullLayoutComponent@50:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("ocial Buttons</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/cards']"><i class="icon-puzzle"></i> Cards</a> </li> 
       <li class="n"): FullLayoutComponent@51:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("e"></i> Cards</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/forms']"><i class="icon-puzzle"></i> Forms</a> </li> 
       <li class="n"): FullLayoutComponent@52:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("e"></i> Forms</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/switches']"><i class="icon-puzzle"></i> Switches</a> </li> 
       <li cl"): FullLayoutComponent@53:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("</i> Switches</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/components/tables']"><i class="icon-puzzle"></i> Tables</a> </li> 
      </ul> </li>"): FullLayoutComponent@54:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/icons/font-awesome']"><i class="icon-star"></i> Font Awesome</a> </li> 
       <li c"): FullLayoutComponent@58:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. (" Font Awesome</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/icons/simple-line-icons']"><i class="icon-star"></i> Simple Line Icons</a> </li> 
  "): FullLayoutComponent@59:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. (" </li> 
      </ul> </li> 
     <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/widgets']"><i class="icon-calculator"></i> Widgets <span class="tag tag-info">NEW</s"): FullLayoutComponent@61:73
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("s="nav-dropdown-items"> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/login']"><i class="icon-star"></i> Login</a> </li> 
       <li class="nav-item"): FullLayoutComponent@66:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("r"></i> Login</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/register']"><i class="icon-star"></i> Register</a> </li> 
       <li class="na"): FullLayoutComponent@67:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("</i> Register</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/404']"><i class="icon-star"></i> Error 404</a> </li> 
       <li class="nav-it"): FullLayoutComponent@68:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("/i> Error 404</a> </li> 
       <li class="nav-item"> <a class="nav-link" routerlinkactive="active" [ERROR ->][routerlink]="['/pages/500']"><i class="icon-star"></i> Error 500</a> </li> 
      </ul> </li> 
    <"): FullLayoutComponent@69:75
Can't bind to 'routerlink' since it isn't a known property of 'a'. ("ss="btn btn-secondary" href="#"><i class="icon-speech"></i></a> 
      <a class="btn btn-secondary" [ERROR ->][routerlink]="['/dashboard']"><i class="icon-graph"></i> &nbsp;Dashboard</a> 
      <a class="btn btn"): FullLayoutComponent@83:35
    at TemplateParser.parse (http://localhost:8080/angular2-starter-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:8525:21)
    at RuntimeCompiler._compileTemplate (http://localhost:8080/angular2-starter-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:16879:53)
    at eval (http://localhost:8080/angular2-starter-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:16802:85)
    at Set.forEach (native)
    at compile (http://localhost:8080/angular2-starter-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:16802:49)
    at ZoneDelegate.invoke (http://localhost:8080/angular2-starter-webapp/node_modules/zone.js/dist/zone.js:203:28)
    at Zone.run (http://localhost:8080/angular2-starter-webapp/node_modules/zone.js/dist/zone.js:96:43)
    at http://localhost:8080/angular2-starter-webapp/node_modules/zone.js/dist/zone.js:462:57
    at ZoneDelegate.invokeTask (http://localhost:8080/angular2-starter-webapp/node_modules/zone.js/dist/zone.js:236:37)
    at Zone.runTask (http://localhost:8080/angular2-starter-webapp/node_modules/zone.js/dist/zone.js:136:47)consoleError @ zone.js:355
zone.js:357 Error: Uncaught (in promise): Error: Template parse errors:(…)consoleError @ zone.js:357

**Comment by eremigio** [comment]
Hola, como solucionaste tu error?
