### ISSUE TITLE
Datetimepicker not working

### ISSUE THREAD

**Issue by iqbalpmgks** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#42]
I want to use the bootstrap datetimepicker in CoreUI but did not run, what's wrong?

**Comment by mrholek** [comment]
In which version?

**Comment by vonchristian** [comment]
bootstrap datepicker https://github.com/uxsolutions/bootstrap-datepicker is also not working on the static full project I downloaded.

**Comment by iqbalpmgks** [comment]
Sorry for late respond, this problem solved. Thank You sir!

**Comment by hhsadiq** [comment]
@iqbalpmgks how you solved it..?

**Comment by goopter** [comment]
can anyone comment if this date time picker is part of the coreui lib?

http://coreui.platform.ims.io/styleguide/components/date-time-picker-input

**Comment by dungmv** [comment]
> can anyone comment if this date time picker is part of the coreui lib?
> 
> http://coreui.platform.ims.io/styleguide/components/date-time-picker-input

How to use in Laravel?

**Comment by eldhojoypappara** [comment]
> Sorry for late respond, this problem solved. Thank You sir!

How you solved it?

**Comment by eldhojoypappara** [comment]
> > can anyone comment if this date time picker is part of the coreui lib?
> > http://coreui.platform.ims.io/styleguide/components/date-time-picker-input
> 
> How to use in Laravel?

How?
