### ISSUE TITLE
About react version

### ISSUE THREAD

**Issue by zsuswy** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#44]
I know that you are working on the React version. Any updates about the progress? If it takes months I will use the Ajax version in my project. Otherwise, I'd like to wait for the React version. By the way, need anyone to help speed it up?

**Comment by cmelgarejo** [comment]
I'm in on helping the React version whenever  👍

**Comment by oytuntez** [comment]
Honestly, I was keen on implementing CoreUI on a current project; but seeing almost none of the issues have been addressed, I think I will not...
