### ISSUE TITLE
Angular2 directives

### ISSUE THREAD

**Issue by Podkekette** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#46]
Hi there :),

I just import your theme on my project. I saw a 'vamiddle' . Did you already write it ? 

Thx,
Laurent.

**Comment by mrholek** [comment]
I was using this directive in Angular version. It is in Angular2 version by mistake.

**Comment by Podkekette** [comment]
Oh no problem but what is your solution for angular2 version ?

**Comment by mrholek** [comment]
You can use following class all versions `.d-table > .d-100vh-va-middle`

**Example:**

`<div class="container d-table">
    <div class="d-100vh-va-middle">
        ...Vertical centered content...
    </div>
</div>`
