### ISSUE TITLE
Two style.css files?

### ISSUE THREAD

**Issue by cyberbobcity** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#47]
You have two style.css files, slightly different in the project. I'm using the Angular2 CLI Starter.

/src/app/assets/style.css
/src/app/assets/css/style.css

They seem very similar... are they both needed?

**Comment by Mavlarn** [comment]
If we use `ng serve` in dev, or `ng build --prod` for prod, there will be styles.js file created, and the css will be imported by this js.
So, none of the css files as above said are used. So I am wondering what are these css files are for?

**Comment by mrholek** [comment]
Fixed in latest version
