### ISSUE TITLE
side menu issue

### ISSUE THREAD

**Issue by s00pa** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#49]
Hi,
firstly, fantastic project. I'm looking forward to using it :)
I'm testing the Angular 2 version in case that makes a difference.
If the side menu is closed while the main window is large and then the main window is resized to narrow to trigger responsive change, opening the side menu will not work (note, if the side menu is not closed prior to resizing the main window then it works as expected)

I hope that's clear enough, let me know if you need further info
## 

Sean

**Comment by wuno** [comment]
Yes I second that. Does anyone have a solution for this? I have been piecing each piece of the app in to a mean stack trying to break it down and understand it. But I have been stuck on the side bar menus. I cant get them to work at all when I port them in but in the angular-cli app its very glitchy which is why I started trying to understand them better. Any info on this would be amazing. Thanks,

**Comment by wuno** [comment]
I am trouble shooting this issue, At first glance if you look at the `<body>` tag notice that default is 
`<body class="navbar-fixed">`

When the sidebar is working without glitch it looks like this,
`<body class="navbar-fixed sidebar-nav mobile-open">`

And when it is not working but still opens showing a blank white box it looks like this,
`<body class="navbar-fixed mobile-open">`

So the missing class is, `sidebar-nav `

If anyone else can see why that is happening or how to fix it let me know. I will update you all if I solve it.

**Comment by mrholek** [comment]
Hi, I will check it and fix ASAP

**Comment by iamonuwa** [comment]
I don't think this issue has been solved. The sidebar has refused to open on smaller screen devices

**Comment by clarkj** [comment]
This issue also persists on Angular 1

**Comment by fabiodisconzi** [comment]
Really fantastic theme.
How to open tha page with the sidebar "minimized" by default? With minimized I mean in 50px large (the width of the sidebar after clicking on
`<button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>`
Thanks!
