### ISSUE TITLE
Feature Datepicker - Angular 2 CLI

### ISSUE THREAD

**Issue by KnightArnold** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#54]
Congrats for the project! I love it!
Will you include a datepicker like angular2-datepicker? 

https://www.npmjs.com/package/angular2-datepicker

It would be a nice idea if the user can pick the date from the datepicker, or to write the date just putting numbers (I mean the bootstrap datepicker will accept something like 10102016, and it will autocomplete the slashes so I will get 10/10/2016)

Thank you for your effort and sharing it!

**Comment by barbatrukko** [comment]
Hello,
I also have the same need. 
Why often these in this kind of Admin Templates the DatePicker component are not provided?
Pending the inclusion of a datepiker in this UI could you sugget me some DatePiker who works well in Angular2 with this UI?
Best regards

**Comment by hhsadiq** [comment]
yeah that will be really helpful to have date picker included in all flavours of this project..

**Comment by type0lang** [comment]
+1

**Comment by mrholek** [comment]
It is available in CoreUI Pro http://coreui.io/pro/angular/
