### ISSUE TITLE
Minified Sidebar Dropdowns

### ISSUE THREAD

**Issue by rubyframework** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#56]
Hi There. 

Would be great if there was a way to access the submenu items when the sidebar is minified (showing icons only). In other templates, when the icons in the mini sidebar is hovered over, it displays the submenu items on the side in a dropdown, your template does not allow access to submenu items when the sidebar is mini currently. Please correct me if I am wrong on this. 

Cheers.

**Comment by mrholek** [comment]
Hi,

I'm working on some new layouts options. It will be available soon.

Regards
Lukasz

**Comment by rubyframework** [comment]
Brilliant! 

Great project by the way, very impressed.
