### ISSUE TITLE
Multiple repositories

### ISSUE THREAD

**Issue by jvitor83** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#58]
> Hi, first, have to say, really like your project! In fact, i am using it (Angular2 Starter) as a starter kit for a seed repo [https://github.com/jvitor83/angular-seed-cli-admin](https://github.com/jvitor83/angular-seed-cli-admin) (which agreggate some features as Mobile, Desktop, Authentication, etc).

What i come to say is to see if you could create a different repository for each directory (project) you have:
- AJAX_Full_Project_GULP
- AJAX_Starter_GULP
- Angular2_CLI_Full_Project
- Angular2_CLI_Starter
- Angular_Full_Project_GULP
- Angular_Starter_GULP
- Static_Full_Project_GULP
- Static_Starter_GULP

That give the possibility to fork your individual project and keep the changes in sync.

> _The way it are, each new commit i have to manually apply._

And even if you want to keep this repo with every other in a sub folder, you could use the git's submodule feature.

**Comment by mrholek** [comment]
We decided to move different versions to separate repositores, so they will support bower and npm soon.

* [Angular Version (Angular 2+)](https://github.com/mrholek/CoreUI-Angular).
* [AngularJS Version](https://github.com/mrholek/CoreUI-AngularJS).
* [HTML5 AJAX Version](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template).
* [HTML5 Static Version](https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template).
* [React.js Version](https://github.com/mrholek/CoreUI-React).
* [Vue.js Version](https://github.com/mrholek/CoreUI-Vue).
