### ISSUE TITLE
css class p-r-2 not work

### ISSUE THREAD

**Issue by Mavlarn** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#62]
I saw the document and scss file `core/utilities-border`, in which some class like 'p-a-0', 'p-r-2' defined.
But when I use angular2 with scss, removed `<link href="assets/css/styles.css" rel="stylesheet">` in index.html. But the classes do not exist.

**Comment by mrholek** [comment]
Hi, those class have been changed in latest version of bootstrap. 

For example: 

- p-a-0 ==> pa-0
- p-r-2 ==> pr-2

I need to upgrade documentation.
