### ISSUE TITLE
Angular 2 : module size is too big

### ISSUE THREAD

**Issue by sanju99785** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#67]
Hi guys,

I have installed npm and folder gets size about 259 mb. Can we reduce that?
If we can remove unwanted package we can decrease it size. 

Thanks,

**Comment by patkar** [comment]
That's angular.. Seems pretty normal for node js stuff. Btw have you the latest npm version or still stuck with npm v2? That's also a factor for the size of node modules.

Btw beside of using your diskspace the size of this folder doesn't matter.

**Comment by sanju99785** [comment]
node version is 5.11.0. Yes size doesn't matter but normally if i get some theme/whole admin theme it is usually about 100 mb.

**Comment by patkar** [comment]
I meant the npm version, not node. They are different ;)

And as mentioned before, that's Angular 2. Simple as that. The Angular base in the theme has already around 110MiB even with flattened node modules. And then all the testing in the devDependencies can grow it towards your 260MiB. Nothing unusual in JS framework projects. That has nothing to do with an admin theme in general..

**Comment by sanju99785** [comment]
sorry, npm version is 3.8.6. I was talking about normal html theme with Jquery. My only concern was does it effect to publish environment with size parameter?

**Comment by patkar** [comment]
Erm, you have installed the angular 2 version, not the jquery version. Compile it and see how big the resulting js files are..
