### ISSUE TITLE
Scrollbar for Aside Panel

### ISSUE THREAD

**Issue by albhardy** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#7]
Thank you for sharing this great admin template! 

A Use Case that I have is to have detailed information of selected item on main panel displayed. Aside Menu on Right Panel seems to be a suitable solution. However, the current Aside does not seem support long information (i.e. it does not have its own scrollbar) - thus user won't be able to view some information.

![image](https://cloud.githubusercontent.com/assets/1732018/17842789/697b93ac-67db-11e6-9955-7f05da5c730b.png)

Do you have any plan to support multiple scrollbars display? Is there any recommended workaround?

**Comment by mrholek** [comment]
Thank you for your feedback. I'm going to add scrollbar for aside panel.

Do you have any plan to support multiple scrollbars display? I don't get it. Can you explain?

**Comment by albhardy** [comment]
Thanks! - I mean if there are multiple panel areas that require scrollbar. For example, in Azure:

![image](https://cloud.githubusercontent.com/assets/1732018/17850619/9afea116-6890-11e6-8ccf-1ea25229a33f.png)

![image](https://cloud.githubusercontent.com/assets/1732018/17850695/0b64ed5c-6891-11e6-8ce0-f23af750172f.png)

My aim is to handle 100% min height and overflow content in either sidebar, main, and/or aside panel.
