### ISSUE TITLE
CoreUI vs Clever

### ISSUE THREAD

**Issue by caglarturkurka** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#70]
Hi, I notice that you announced new angular 2,bootstrap 4 and HTML 5 template which is called as Clever.Please tell me which one is good and wich one will be more updated by you in the future.Because I want to decide correct template for my project.
Thanks for your attention

**Comment by mrholek** [comment]
Hi Clever is my Premium Template. Clever has all CoreUI features and additional third party plugins. All my templates will be updated at the same time. Each choice will be good.

**Comment by caglarturkurka** [comment]
Can we use Clever template as free or not.Because we can clone or download it from your Github repository.

**Comment by mrholek** [comment]
No Clever is our premium template so you have to buy license.

**Comment by caglarturkurka** [comment]
Okey thanks for your reply.Also we want to ask a question about CoreUI template because of select box of CoreUI template has a problem with text area.For example, If you use "y" character as a value of select box.Padding problem will be occured.Please tell me when will you update CoreUI-Free-Bootstrap Admin Template

**Comment by cocowalla** [comment]
@caglarturkurka I fixed this with:

```
select.form-control {
  padding: 0rem 0.75rem;
}
```
