### ISSUE TITLE
responsive menu does not close on click

### ISSUE THREAD

**Issue by aep** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#80]
On any of your angular2 themes, when on mobile, the sidebar does not close when clicking a menu entry.

Not sure if this is a fundamental issue or just a configuration option

**Comment by suprcodr** [comment]
Has anyone figured this out yet?

**Comment by kareljuricka** [comment]
@mrholek  seems that in angular4 project this still doesn't work. When I click on link in sidebar on mobile, menu does not close.
