### ISSUE TITLE
When will you update Angular2_CLI_Starter ?

### ISSUE THREAD

**Issue by caglarturkurka** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#82]
Hi, I wonder that when will you update Angular2_CLI_Starter project.Thanks for your attention and your work

**Comment by mrholek** [comment]
I'm working on some updates. I hope it will be ready after xmas.

**Comment by caglarturkurka** [comment]
Thank you for your attention

**Comment by mrholek** [comment]
Updated
