### ISSUE TITLE
Modal, Tooltip etc. Does Not Work

### ISSUE THREAD

**Issue by Crypt0Graphic** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#88]
I downloaded today and setup Angular2_CLI_Full_Project. After everything i noticed modal sample does not work.  I added ng2-bootstrap ToolTip. It does not work also. In my project or in orginal one. 

Not nice after so much work.

**Comment by Crypt0Graphic** [comment]
Samples in your docs are not working also:

http://coreui.io/docs/components/modal

http://coreui.io/docs/components/tooltips

**Comment by MirzaAbazovic** [comment]
Using http://valor-software.com/ng2-bootstrap/#/modals has same behaviour

**Comment by dantavo** [comment]
I have the same problem, I try to use other libreries but nothing, everything fail

**Comment by MarkyMarkNo1** [comment]
Hi @mrholek, regarding **Modals in Angular2_CLI_Full_Project**: 

While adding CSS class `.in` made Modals appear in BS3, `.show` seems to be appropriate in BS4. 

After some investigations i stumbled over these lines in ng2-bootstrap -

[src/modal/modal.component.ts](https://github.com/valor-software/ng2-bootstrap/blob/08bbceb7c4b2cd28dd9228640be7d2d70ba9aad9/src/modal/modal.component.ts#L168):

```
this._renderer.setElementClass(this._element.nativeElement, modal_options_class_1.ClassName.IN, false);
if (!ng2_bootstrap_config_1.isBs3()) {
    this._renderer.setElementClass(this._element.nativeElement, modal_options_class_1.ClassName.SHOW, false);
}

```

[src/utils/ng2-bootstrap-config.ts](https://github.com/valor-software/ng2-bootstrap/blob/08bbceb7c4b2cd28dd9228640be7d2d70ba9aad9/src/utils/ng2-bootstrap-config.ts#L3):

```
export function isBs3(): boolean {
  return window.__theme !== 'bs4';
}
```

**To make a long story short:** adding 

```
<!-- Enable bootstrap 4 theme -->
<script>window.__theme = 'bs4';</script>
```

to [index.html](https://github.com/valor-software/ng2-bootstrap/blob/08bbceb7c4b2cd28dd9228640be7d2d70ba9aad9/demo/src/index-bs4.html#L38) solves and makes Modals appear.

Regards, thank you for your efforts!

**Comment by dantavo** [comment]
I insert this line into index.html but nothing change the problem still remain
