### ISSUE TITLE
Suggestion for React Flavor of template

### ISSUE THREAD

**Issue by CharlieMarket** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#89]
React Bootstrap 4 components can save you a lot of time in development.
https://reactstrap.github.io/

If you have a code base for react I offer to work on it :-)

**Comment by eddywashere** [comment]
If you do consider reactstrap, please don't hesitate to create an issue or ping me if there's anything you need. I've been meaning to put a sample app up and would be happy to link out to this. Thanks!

**Comment by mrholek** [comment]
Thank you, first version of React version with reactstrap on boards is ready
