### ISSUE TITLE
Is it safe to use this temple for production

### ISSUE THREAD

**Issue by hhsadiq** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#98]
Hey guys,

Since this template is using boostrap4 which is still in alpha version, so is it safe to use this template for production?

**Comment by mrholek** [comment]
Finall version of Bootstrap 4 is just around the corner. So you can use this template in production.

I know that some big companies and organisations use CoreUI and they don't report any problems.

**Comment by hhsadiq** [comment]
Great, thanks a lot for reply. I am now using it for production app 💯
