### ISSUE TITLE
aot compilation ?

### ISSUE THREAD

**Issue by pomeara** [mrholek/CoreUI-Free-Bootstrap-Admin-Template#99]
Can you confirm that the aot is working with Core UI ? From what I've read about in the angular-cli documentation the commands are 

ng build --prod --aot and
ng serve --prod --aot

I've actually just done a little reading and have tried the above two lines and it appears to be doing the right stuff.  Perhaps an update to the readme.md to include these two commands to point people in the right direction unless there is something that I've missed.

Thanks in advance and great work too!

**Comment by mrholek** [comment]
Yes aot is working with CoreUI.
